#!/usr/bin/env python3
"""
fetch_screener_docs.py
──────────────────────
Discovers all documents listed on a Screener.in company page and returns
structured metadata (name, date, url, category) — WITHOUT downloading them.

Can operate on:
  • A single stock   →  --ticker ASIANPAINT
  • Multiple stocks  →  --ticker HUL TCS INFY
  • All stocks from the CSV generated by fetch_screener_tickers.py
      →  --csv screener_tickers.csv

Output is a JSON file (one entry per stock) with every document's metadata.

Requirements (same venv as the main scraper):
    requests, beautifulsoup4, lxml, tqdm
"""

import argparse
import csv
import json
import logging
import random
import re
import socket
import time
from pathlib import Path

import requests
from bs4 import BeautifulSoup
from tqdm import tqdm

# ─── CONFIG ──────────────────────────────────────────────────────────────────

SCREENER_BASE = "https://www.screener.in"
PAGE_DELAY = 1.5  # seconds between company page requests (be polite)

# Default path to the tickers CSV (generated by fetch_screener_tickers.py)
DEFAULT_TICKERS_CSV = Path(__file__).parent / "screener_tickers.csv"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.screener.in/",
}

# ─── LOGGING ─────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ─── NETWORK RESILIENCE ─────────────────────────────────────────────────────

CONNECTIVITY_CHECK_HOST = "www.screener.in"
CONNECTIVITY_CHECK_PORT = 443
CONNECTIVITY_POLL_INTERVAL = 2


def _is_online() -> bool:
    try:
        sock = socket.create_connection(
            (CONNECTIVITY_CHECK_HOST, CONNECTIVITY_CHECK_PORT), timeout=5
        )
        sock.close()
        return True
    except OSError:
        return False


def wait_for_connection() -> None:
    if _is_online():
        return
    log.warning("⏸  Network down — waiting for connection…")
    while not _is_online():
        time.sleep(CONNECTIVITY_POLL_INTERVAL)
    log.info("▶  Connection restored — resuming.")


def resilient_get(session: requests.Session, url: str, **kwargs) -> requests.Response:
    """GET with automatic retry on network errors."""
    while True:
        wait_for_connection()
        try:
            resp = session.get(url, **kwargs)
            return resp
        except (
            requests.exceptions.ConnectionError,
            requests.exceptions.Timeout,
            requests.exceptions.ChunkedEncodingError,
            OSError,
        ) as exc:
            log.warning("  Network error: %s — retrying…", exc)
            wait_for_connection()


# ─── PARSING ─────────────────────────────────────────────────────────────────

# Maps sub-section heading text → normalised category key
CATEGORY_MAP = {
    "annual report":   "annual_reports",
    "annual reports":  "annual_reports",
    "credit rating":   "credit_ratings",
    "credit ratings":  "credit_ratings",
    "concall":         "concalls",
    "concalls":        "concalls",
    "conference call": "concalls",
    "announcement":    "announcements",
    "announcements":   "announcements",
    "exchange filing": "announcements",
    "presentation":    "presentations",
    "presentations":   "presentations",
    "important":       "Important"
}
 
# Date patterns commonly seen in Screener doc labels
#   "Financial Year 2024"  or  "10 Sep 2025"  or  "Feb 2026"  or  "31 Mar"
_DATE_PATTERNS = [
    # "Financial Year 2025"
    re.compile(r"Financial\s+Year\s+(\d{4})", re.I),
    # "10 Sep 2025"  or  "31 Mar 2026"
    re.compile(
        r"(\d{1,2}\s+"
        r"(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+"
        r"\d{4})",
        re.I,
    ),
    # "Feb 2026"  or  "Nov 2025"
    re.compile(
        r"((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{4})",
        re.I,
    ),
    # year only at end  e.g. "... 2024"
    re.compile(r"\b(20\d{2})\b"),
]


def _extract_date(text: str) -> str | None:
    """Try to pull a date string from document label text."""
    for pat in _DATE_PATTERNS:
        m = pat.search(text)
        if m:
            return m.group(1) if m.lastindex else m.group(0)
    return None


def parse_documents(html: str, ticker: str) -> list[dict]:
    """
    Parse the #documents section of a Screener company page and return
    a flat list of document metadata dicts:

        {
            "ticker":   "ASIANPAINT",
            "category": "annual_reports",
            "name":     "Financial Year 2025 from bse",
            "date":     "2025",
            "url":      "https://www.bseindia.com/xml-data/..."
        }
    """
    soup = BeautifulSoup(html, "lxml")
    documents: list[dict] = []

    # Find #documents section
    doc_section = soup.find(id="documents")
    if not doc_section:
        for heading in soup.find_all(["h2", "h3", "h4", "section"]):
            if "document" in heading.get_text(strip=True).lower():
                doc_section = heading.find_parent(["section", "div"]) or heading
                break

    if not doc_section:
        log.debug("  No #documents section for %s", ticker)
        return documents

    # Walk the DOM to categorise links
    current_category: str | None = None
    current_period: str | None = None  # for concall date grouping

    for el in doc_section.descendants:
        if not hasattr(el, "name") or el.name is None:
            # Text nodes — may carry the concall period (e.g. "Feb 2026")
            text = str(el).strip()
            if text and current_category == "concalls":
                date = _extract_date(text)
                if date:
                    current_period = date
            continue

        # Detect sub-section headings (h2-h5)
        if el.name in ("h2", "h3", "h4", "h5"):
            heading_text = el.get_text(strip=True).lower()
            matched = False
            for key, cat in CATEGORY_MAP.items():
                if key in heading_text:
                    current_category = cat
                    matched = True
                    break
            if not matched:
                current_category = None
            current_period = None
            continue

        # Detect concall list items — they carry the period
        if el.name == "li" and current_category == "concalls":
            li_text = el.get_text(" ", strip=True)
            date = _extract_date(li_text)
            if date:
                current_period = date

        # Harvest links
        if el.name == "a" and current_category:
            href = el.get("href", "").strip()
            if not href or href.startswith("#") or "screener.in/login" in href:
                continue

            # Resolve relative URLs
            if href.startswith("/"):
                href = SCREENER_BASE + href

            label = el.get_text(" ", strip=True) or el.get("title", "")
            title_attr = el.get("title", "")

            # Determine doc type for concalls (Transcript / PPT / REC)
            doc_type = None
            label_lower = label.lower()
            if "transcript" in label_lower or "transcript" in title_attr.lower():
                doc_type = "transcript"
            elif "ppt" in label_lower or "presentation" in label_lower:
                doc_type = "ppt"
            elif "rec" in label_lower or "youtu" in href:
                doc_type = "recording"

            # Build the display name
            if current_category == "concalls" and current_period:
                name = current_period
            elif label:
                name = re.sub(r"\s+", " ", label)
            else:
                name = href.split("/")[-1]

            # Extract date from label
            date = _extract_date(label) or current_period or _extract_date(name)

            documents.append({
                "ticker":   ticker,
                "category": current_category,
                "doc_type": doc_type,
                "name":     name,
                "date":     date,
                "url":      href,
            })

    return documents


# ─── LLM-READY FILTERING ────────────────────────────────────────────────────


def filter_docs_for_llm(
    docs: list[dict],
    max_presentations: int = 8,
) -> dict:
    """
    Filter raw document metadata to the most useful items for LLM consumption:
      • Annual Reports       (all available)
      • Concall transcripts  (all available)
      • Investor presentations / PPTs  (latest N)
      • Credit ratings       (all available)
      • Announcements        (all available)
      • Important            (all available)

    Returns a dict with corresponding keys, each containing a list of slim dicts.
    """
    annual_reports = [
        d for d in docs
        if d["category"] == "annual_reports"
    ]
    transcripts = [
        d for d in docs
        if d["category"] == "concalls" and d.get("doc_type") == "transcript"
    ]
    presentations = [
        d for d in docs
        if (d["category"] == "concalls" and d.get("doc_type") == "ppt") or (d["category"] == "presentations")
    ][:max_presentations]  # keep only latest N
    credit_ratings = [
        d for d in docs
        if d["category"] == "credit_ratings"
    ]
    announcements = [
        d for d in docs
        if d["category"] == "announcements"
    ]
    important = [
        d for d in docs
        if d["category"] == "Important"
    ]

    # Slim each entry to just what the LLM needs
    def _slim(d: dict) -> dict:
        return {
            "name": d["name"],
            "date": d.get("date"),
            "url":  d["url"],
        }

    return {
        "annual_reports": [_slim(d) for d in annual_reports],
        "transcripts":    [_slim(d) for d in transcripts],
        "presentations":  [_slim(d) for d in presentations],
        "credit_ratings": [_slim(d) for d in credit_ratings],
        "announcements":  [_slim(d) for d in announcements],
        "Important":      [_slim(d) for d in important],
    }


def format_docs_for_llm(
    docs: list[dict],
    ticker: str | None = None,
    max_presentations: int = 8,
) -> str:
    """
    One-shot utility: filter + format document metadata into a compact,
    numbered text block ready to paste into an LLM prompt.
    """
    filtered = filter_docs_for_llm(docs, max_presentations=max_presentations)

    if ticker is None and docs:
        ticker = docs[0].get("ticker", "UNKNOWN")

    lines: list[str] = []
    lines.append(f"## Available Documents for {ticker}\n")

    idx = 1

    def add_section(title: str, items: list[dict], is_latest: bool = False, max_items: int | None = None):
        nonlocal idx
        if is_latest and max_items and len(items) == max_items:
            label = f"latest {max_items}"
        else:
            label = f"{len(items)} available"

        lines.append(f"### {title} ({label})")
        if not items:
            lines.append("  (none found)")
        for d in items:
            date_str = d.get("date") or "unknown date"
            if title in ["Concall Transcripts", "Investor Presentations"]:
                lines.append(f"[{idx}] {date_str}  —  {d['url']}")
            else:
                lines.append(f"[{idx}] {d['name']}, {date_str}  —  {d['url']}")
            idx += 1
        lines.append("")

    add_section("Annual Reports", filtered["annual_reports"])
    add_section("Concall Transcripts", filtered["transcripts"])
    add_section("Investor Presentations", filtered["presentations"], is_latest=True, max_items=max_presentations)
    add_section("Credit Ratings", filtered["credit_ratings"])
    add_section("Announcements", filtered["announcements"])
    add_section("Important", filtered["Important"])

    return "\n".join(lines)


# ─── TICKER REGISTRY (CSV → URL lookup) ─────────────────────────────────────


class TickerRegistry:
    """
    Loads screener_tickers.csv once and provides O(1) ticker → URL lookups.
    """

    def __init__(self, csv_path: str | Path = DEFAULT_TICKERS_CSV):
        self._map: dict[str, str] = {}  # ticker → screener_url
        csv_path = Path(csv_path)
        if not csv_path.exists():
            log.warning(
                "Tickers CSV not found at %s — URL lookup will fall back to pattern.",
                csv_path,
            )
            return
        with open(csv_path, newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                self._map[row["ticker"]] = row["screener_url"]
        log.info("TickerRegistry: loaded %d tickers from %s", len(self._map), csv_path)

    def get_url(self, ticker: str) -> str | None:
        """Return the Screener URL for a ticker, or None if not found."""
        return self._map.get(ticker) or self._map.get(ticker.upper())

    def __len__(self) -> int:
        return len(self._map)

    def __contains__(self, ticker: str) -> bool:
        return ticker in self._map or ticker.upper() in self._map


# Module-level singleton — loaded lazily on first use
_registry: TickerRegistry | None = None


def get_ticker_registry(csv_path: str | Path = DEFAULT_TICKERS_CSV) -> TickerRegistry:
    """Return (and cache) the global TickerRegistry."""
    global _registry
    if _registry is None:
        _registry = TickerRegistry(csv_path)
    return _registry


# ─── FETCHING ────────────────────────────────────────────────────────────────


def fetch_documents_for_stock(
    session: requests.Session,
    ticker: str,
    screener_url: str | None = None,
) -> list[dict]:
    """
    Fetch and parse all document metadata for a single stock.

    Args:
        session:      requests session with headers set.
        ticker:       e.g. "ASIANPAINT".
        screener_url: full URL or path. If None, looks up the URL from
                      screener_tickers.csv via the TickerRegistry.

    Returns:
        List of document metadata dicts.
    """
    # Resolve URL: explicit arg  →  CSV lookup  →  pattern fallback
    if screener_url is None:
        registry = get_ticker_registry()
        screener_url = registry.get_url(ticker)

    if screener_url is not None:
        if screener_url.startswith("/"):
            screener_url = SCREENER_BASE + screener_url
        urls_to_try = [screener_url]
    else:
        # Last resort: guess pattern (no CSV available or ticker not in CSV)
        log.debug("  %s: not in CSV, falling back to URL pattern", ticker)
        urls_to_try = [
            f"{SCREENER_BASE}/company/{ticker}/consolidated/",
            f"{SCREENER_BASE}/company/{ticker}/",
        ]

    for url in urls_to_try:
        try:
            resp = resilient_get(session, url, timeout=20)
            if resp.status_code == 404:
                log.debug("  %s: 404 at %s, trying next…", ticker, url)
                continue
            resp.raise_for_status()
        except requests.exceptions.RequestException as exc:
            log.warning("  Failed to fetch page for %s: %s", ticker, exc)
            continue

        docs = parse_documents(resp.text, ticker)
        log.info("  %s: found %d documents (%s)", ticker, len(docs), url)
        return docs

    log.warning("  %s: all URLs failed", ticker)
    return []


def load_tickers_from_csv(csv_path: str) -> list[dict]:
    """
    Read the CSV produced by fetch_screener_tickers.py.
    Expected columns: stock_name, ticker, screener_url
    """
    tickers = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            tickers.append({
                "stock_name":   row["stock_name"],
                "ticker":       row["ticker"],
                "screener_url": row["screener_url"],
            })
    log.info("Loaded %d tickers from %s", len(tickers), csv_path)
    return tickers


# ─── CLI ─────────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        description="List all documents for stocks from Screener.in (metadata only, no downloads)"
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--ticker", nargs="+", metavar="SYMBOL",
        help="One or more ticker symbols  (e.g. --ticker HUL TCS INFY)",
    )
    group.add_argument(
        "--csv", metavar="CSV_PATH",
        help="Path to the tickers CSV from fetch_screener_tickers.py",
    )
    parser.add_argument(
        "-o", "--output", default="screener_docs_index.json",
        help="Output JSON path (default: screener_docs_index.json)",
    )
    parser.add_argument(
        "--limit", type=int, default=None,
        help="Process only the first N stocks (for testing)",
    )
    args = parser.parse_args()

    session = requests.Session()
    session.headers.update(HEADERS)

    # Build stock list
    if args.csv:
        stocks = load_tickers_from_csv(args.csv)
    else:
        # Look up URLs from the CSV registry
        registry = get_ticker_registry()
        stocks = []
        for t in args.ticker:
            ticker = t.upper()
            url = registry.get_url(ticker)
            if url is None:
                log.warning("Ticker %s not found in CSV — will try URL patterns", ticker)
            stocks.append({"ticker": ticker, "screener_url": url})

    if args.limit:
        stocks = stocks[: args.limit]
        log.info("Limiting to first %d stocks.", args.limit)

    # Process each stock
    all_docs: dict[str, list[dict]] = {}
    for stock in tqdm(stocks, desc="Fetching doc listings", unit="stock"):
        ticker = stock["ticker"]
        url = stock.get("screener_url")
        docs = fetch_documents_for_stock(session, ticker, url)
        all_docs[ticker] = docs
        time.sleep(PAGE_DELAY + random.random())

    # Save output
    output_path = Path(args.output)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(all_docs, f, indent=2, ensure_ascii=False)

    total = sum(len(v) for v in all_docs.values())
    log.info("═" * 60)
    log.info(
        "Done. Stocks: %d  |  Total documents indexed: %d  |  Saved to: %s",
        len(all_docs), total, output_path,
    )


if __name__ == "__main__":
    main()
